development:
  adapter: postgresql
  database: mypage_development
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: mypage_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mypage_production
  pool: 5
  timeout: 5000